// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/remix-nitro@0.0.9_react-dom@18.2.0_react@18.2.0_typescript@5.1.6/node_modules/remix-nitro/routes/index').default>>>>
    }
    '/test': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../routes/test').default>>>>
    }
    '/api/v1/test2': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/v1/test2').default>>>>
    }
  }
}
export {}